### PR TITLE
Improve handling of [NoLineTerminatorHere]

### LINKED ISSUE #7: Incorrect parsing of async declarations containing comments
The sequence

```
async /* x */ function a() {} 
```

...incorrectly parses as a FunctionExpression, not a FunctionDeclaration

```
async /* x */
function a() {}
```

...incorrectly parses as an async FunctionExpression (it should be a reference to the identifier 'async' and a FunctionDeclaration). Single line comments fail similarly

### PR DESCRIPTION
**Pull request by caitp**
Closes #7

### CODE REVIEW

**Comment by caitp** [comment]
This fixes the aspects that are most obviously broken, and likely sees a bit of a performance improvement due to slightly less RegExp matching. The ExportDeclaration parsing still looks a bit fishy, though.

**Comment by MatAtBread** [comment]
I did this a different way, but yours is much better :), so I'm picking apart the changes to make sure it covers both issues (the comments, and the incorrect parsing of `async\nfunction x(){}` which parses the second statement as a FunctionExpression. Give me a couple of hours

**Comment by MatAtBread** [comment]
I'm intrigued by this test case:

```
    describe('linefeed after async (multiline comment) function', () => {
      var ast;
      beforeEach(() => {
        ast = parse([
          'async /* flag enables async completion',
          '         of the callback */function foo() {',
          '}'
        ]);
      });

      it('finds Identifier ExpressionStatement', () => {
        assertFindsIdentifierExpressionStatement(ast);
      });

      it('does not mark FunctionDeclaration as async', () => {
        node = find('FunctionDeclaration', ast);
        assert(!node.async, 'Expected node.async to be false');
      });
    });
  });

```

I think your test is relying on a current (broken) case. The resulting ast shouldn't in fact be a FunctionExpression, but an async FunctionDeclaration (since the `async function...` isn't in parenthesis or otherwise part of an expression, or un-named). 

When I was testing yesterday I found that any comment after async causes this error (an unfortunate test within acorn that I'd managed to misunderstand), which I've now patched, but this breaks your test.

Can you confirm that your understanding is the same as mine, that is should be an async FunctionDeclaration?

**Comment by caitp** [comment]
The linefeed in the multiline comment precludes it from being an async function. So you end up with `Identifier("async")` -> `PrimaryExpression` -> `ExpressionStatement`. The following line is a new `Statement` in the `StatementList`, which is parsed as a non-async `FunctionDeclaration`.

**Comment by caitp** [comment]
Try the following code in any implementation that supports async functions:

``` js
var async = 1;
function f() {
  async /* multiline comment
  */function f() { await 1; }
}
```

It should be a syntax error, as the AwaitExpression is used in a non-async function (including the [babel repl](https://babeljs.io/repl/#?evaluate=true&lineWrap=false&presets=es2015%2Creact%2Cstage-2%2Cstage-3&code=var%20async%20%3D%201%3B%0Afunction%20f%28%29%20%7B%0A%20%20async%20%2F*%20multiline%20comment%0A%20%20*%2Ffunction%20f%28%29%20%7B%20await%201%3B%20%7D%0A%7D), to simplify reproducing)

**Comment by caitp** [comment]
@bterlson if you have time to confirm my read of the grammar, that would be helpful, but no pressure

**Comment by MatAtBread** [comment]
Wow... I'm just a humble implementor (and tree surgeon), so I'm not in a position to comment. I do however find it pretty counter-intuitive that:

```
async /* comment */ function x() { }
```

...is an async function decl, but 

```
async /* comment
comment */ function x() {}
```

is not. I'll tweak a bit more and try and get it right

**Comment by caitp** [comment]
unfortunately, automatic semicolon insertion makes this necessary :( Otherwise the async function proposal could break existing code (unlikely, but the web is a weird place :()

**Pull request merged**
